"""
Phase 10.2 slot 12 - One-Minute Concept Animation Storyboard
An actual video file cannot be generated by this pipeline, so this produces a
detailed, production-ready STORYBOARD for the required 1-minute concept animation
(the competition permits AI tools for the video). This is an honest deliverable:
it hands a video editor / AI-video tool exact shot-by-shot direction.
"""

import os
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "01_PHASE1_EXISTING_PARK", "_scripts"))
from report_builder import build_report

DEST = os.path.join(os.path.dirname(__file__), "..", "10.2_Required_Files", "12_Concept_Animation_Video")
os.makedirs(DEST, exist_ok=True)

sections = [
    {"type": "para", "text": (
        "<b>Storyboard for the required 1-minute concept animation.</b> An actual video is not "
        "generated by the analysis pipeline; this document gives shot-by-shot direction so the "
        "video can be produced (AI video tools are permitted by the brief for this deliverable). "
        "All visuals referenced already exist in the submission package."
    )},
    {"type": "heading", "text": "Concept & Tone"},
    {"type": "para", "text": (
        "60 seconds. Calm, confident, evidence-led. Warm sand/stone palette. Message: "
        "\"AI helped us prove how to make this park usable all year — the design puts people "
        "and shade first.\" Voiceover optional; on-screen text captions required."
    )},
    {"type": "heading", "text": "Shot List (60s)"},
    {"type": "table", "header": ["Time", "Visual", "Caption / VO", "Source Asset"], "rows": [
        ["0-6s", "Aerial context: Al Safa 2 in Dubai, zoom to the park site", "\"Al Safa 2 Park — 15,000 m², 7,640 neighbours within a 10-min walk.\"", "master-plan location image + catchment_rings.png"],
        ["6-14s", "The problem: sun rising to overhead, park surface glowing hot", "\"Dubai's summer sun sits almost overhead — normal shade fails at noon.\"", "fullyear_elevation_heatmap.png / sun path"],
        ["14-22s", "Data montage: temperature, sunshine, shadow charts animating in", "\"So we measured it — every hour of the year.\"", "chart_temperature_humidity, fullyear_daily_peak_elevation"],
        ["22-32s", "The idea: the Shaded Spine draws itself across the plan, rooms appear", "\"One continuous shaded spine connects everything.\"", "masterplan_diagram.png"],
        ["32-42s", "Shade simulation plays across seasons; spine stays covered", "\"99.2% shaded, all year — proven, not promised.\"", "shade_coverage_simulation, annual_shade_hours_by_zone"],
        ["42-50s", "Section reveal: people walking shaded; trees, water-wise planting", "\"Native planting. A real ~5,700 m³/year water budget.\"", "section_shaded_spine, water_demand_monthly"],
        ["50-58s", "Day-to-night dissolve of the aerial render; lights come on", "\"A park for all ages, day and night, all seasons.\"", "aerial_day.png -> aerial_night.png"],
        ["58-60s", "Logo lockup: Dubai Municipality AI Park Design Challenge", "\"The Shaded Spine — Al Safa 2 Park.\"", "title card"],
    ]},
    {"type": "heading", "text": "Production Notes"},
    {"type": "bullets", "items": [
        "Format: 1920x1080, 25/30fps, ≤1 minute, exported to a common format then zipped "
        "(the submission form accepts zip/pdf for this slot, max 100MB).",
        "All chart/render assets are in the phase output folders and can be used directly or "
        "re-rendered at higher resolution.",
        "If an AI video tool is used, disclose it in the AI Methodology Report (slot 6) for "
        "consistency with the brief's transparency requirement.",
    ]},
]

build_report(
    output_path=os.path.join(DEST, "Concept_Animation_Storyboard.pdf"),
    phase_tag="ANIMATION STORYBOARD",
    title="One-Minute Concept Animation — Storyboard",
    subtitle="Al Safa 2 Park — Production-Ready Shot List",
    sections=sections,
    code_ref=None,
)

# Also drop a README note in the folder
with open(os.path.join(DEST, "README_VIDEO.txt"), "w", encoding="utf-8") as f:
    f.write("SLOT 12 - ONE-MINUTE CONCEPT ANIMATION\n")
    f.write("=" * 45 + "\n\n")
    f.write("This folder contains a production-ready STORYBOARD "
            "(Concept_Animation_Storyboard.pdf).\n\n")
    f.write("The actual video file is NOT auto-generated by the analysis pipeline. To\n")
    f.write("complete this slot, produce the 60-second video following the storyboard\n")
    f.write("(AI video tools are permitted by the brief), export it, and place it here.\n")
    f.write("This slot is OPTIONAL per the submission form (all others are mandatory).\n")
print("Saved storyboard + README_VIDEO.txt")
