import os
from report_builder import build_report

HERE = os.path.dirname(__file__)
OUT_DIR = os.path.join(HERE, "..", "12_AI_Analysis", "outputs")
os.makedirs(OUT_DIR, exist_ok=True)

sections = [
    {"type": "heading", "text": "1. Purpose"},
    {"type": "para", "text": (
        "This log documents how AI was used to assist Phase 1 (Existing Site Understanding), "
        "satisfying the Brief's explicit requirement (Schedule 1, Section C) that participants "
        "document AI usage throughout the design process — starting from this first phase."
    )},
    {"type": "heading", "text": "2. Tools Used in Phase 1"},
    {"type": "table", "header": ["Tool", "Role"], "rows": [
        ["Claude (Anthropic)", "Orchestration of the analysis workflow; synthesis of written "
         "findings from source PDFs/images; SWOT synthesis logic; identification of data gaps "
         "vs. available facts"],
        ["Python (pandas, matplotlib, numpy)", "Quantitative computation and chart generation"],
        ["pvlib (NREL Solar Position Algorithm)", "Exact astronomical solar position "
         "computation for the site's precise lat/lon — Climate Analysis (1.05) and Shadow "
         "Analysis (1.06)"],
        ["Pillow / numpy (image processing)", "Color-threshold pixel analysis of the "
         "master-plan graphic to estimate visible green-canopy footprint and site bounding box"],
        ["ReportLab", "Programmatic PDF report generation with embedded charts, tables, and "
         "source-code proof appendices"],
    ]},
    {"type": "heading", "text": "3. Areas of Application"},
    {"type": "bullets", "items": [
        "<b>Site data analysis and interpretation</b> — automated extraction from the "
        "master-plan image and structured compilation of brief/manual text.",
        "<b>Mapping and visualization of spatial information</b> — sun-path polar diagram, "
        "shadow direction plan-view diagram, wind rose, SWOT matrix — all generated "
        "programmatically, ensuring traceable, reproducible numbers.",
        "<b>Environmental analysis</b> — solar radiation, temperature, humidity, wind, and "
        "shadow-casting computed using real astronomical formulas, not estimated by eye.",
    ]},
    {"type": "heading", "text": "4. Role of Human Judgment (this session)"},
    {"type": "bullets", "items": [
        "AI (Claude) was directed by the user's explicit phase structure and file scope — it "
        "did not invent the 10-phase framework or analysis categories.",
        "Every claim in the Phase 1 documents is tagged as either (a) sourced directly from "
        "the competition brief/manual/image, (b) computed via a verifiable formula/library, "
        "or (c) an explicitly flagged data gap.",
        "No design decisions (zoning, layout, planting choices, etc.) were made in this phase.",
    ]},
    {"type": "heading", "text": "5. Reproducibility"},
    {"type": "para", "text": (
        "All charts/tables in Phase 1 were generated by scripts in "
        "01_PHASE1_EXISTING_PARK/_scripts/ and can be re-run to regenerate identical outputs — "
        "satisfying the Brief's ask for an AI methodology and workflow that shows genuine, "
        "traceable process rather than a black box."
    )},
]

build_report(
    output_path=os.path.join(OUT_DIR, "Phase1.12_AI_Analysis_Report.pdf"),
    phase_tag="PHASE 1.12 — AI ANALYSIS",
    title="AI Analysis",
    subtitle="Al Safa 2 Park — AI Methodology Log for Phase 1",
    sections=sections,
    code_ref=None,
)
