"""Generate LINKS.md — every public URL this submission can point a juror at.

WHY THIS EXISTS
---------------
The AI Methodology Report is the one place a juror can be *shown* that the
analysis is real rather than asserted, and a link costs one line. But a link
that 404s is worse than no link at all, so these are generated from the files
that actually exist on disk rather than typed from memory. Re-run this after
adding or renaming anything you intend to link to.

GitHub renders PDFs in the browser, so a `/blob/` link to a report opens it
directly — no download, no clone. That is what makes this worth doing.

    python tools/build_links.py
"""

from __future__ import annotations

import subprocess
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import config as C  # noqa: E402

BRANCH = "main"
BLOB = f"{C.GITHUB_URL}/blob/{BRANCH}"
RAW = (f"https://raw.githubusercontent.com/{C.GITHUB_USER}/"
       f"{C.GITHUB_REPO}/{BRANCH}")


def enc(rel: str) -> str:
    """URL-encode each path segment, leaving the separators alone."""
    return "/".join(urllib.parse.quote(part) for part in rel.split("/"))


def link(rel: str) -> str:
    return f"{BLOB}/{enc(rel)}"


def has_remote() -> bool:
    try:
        out = subprocess.run(["git", "remote"], cwd=ROOT, capture_output=True,
                             text=True, timeout=10)
        return bool(out.stdout.strip())
    except Exception:
        return False


def rows(folder: str, pattern: str = "*") -> list[tuple[str, str]]:
    base = ROOT / folder
    if not base.exists():
        return []
    return [(p.name, f"{folder}/{p.name}")
            for p in sorted(base.glob(pattern)) if p.is_file()]


def main() -> int:
    pushed = has_remote()
    L: list[str] = []
    add = L.append

    add("# Links — every URL this submission can point at")
    add("")
    add("*Generated by `python tools/build_links.py` from the files that "
        "actually exist. Re-run it after renaming anything.*")
    add("")

    if not pushed:
        add("> ## ⚠️ NONE OF THESE WORK YET")
        add(">")
        add("> This repository has **no git remote configured** — it has never "
            "been pushed. Every link below will 404 until you complete the "
            "three steps in §1.")
        add(">")
        add("> **Do not put these URLs in the submission until you have "
            "clicked them yourself and seen them load.** A dead link in the AI "
            "Methodology Report is worse than no link: it invites a juror to "
            "check, and then fails in front of them.")
        add("")

    add("---")
    add("")
    add("## 1. Make the links live")
    add("")
    add("### Step 1 — check nothing private is about to be published")
    add("")
    add("```bash")
    add("git ls-files | grep -i UPLODED     # must print NOTHING")
    add("git ls-files | grep _TRASH         # must print NOTHING")
    add("```")
    add("")
    add("`00_BRIEF/UPLODED DOCUMENT DETAILS.txt` holds your **email address and "
        "mobile number**. It is gitignored, but verify it before making the "
        "repository public — once pushed, it is in the history permanently.")
    add("")
    add("### Step 2 — create the repository and push")
    add("")
    add("```bash")
    add(f"gh repo create {C.GITHUB_REPO} --public --source=. --remote=origin")
    add(f"git push -u origin {BRANCH}")
    add("```")
    add("")
    add("Or, if you make the repo on github.com by hand:")
    add("")
    add("```bash")
    add(f"git remote add origin {C.GITHUB_URL}.git")
    add(f"git push -u origin {BRANCH}")
    add("```")
    add("")
    add("### Step 3 — turn on GitHub Pages for the portal")
    add("")
    add(f"On {C.GITHUB_URL}/settings/pages set **Source = Deploy from a "
        f"branch**, **Branch = `{BRANCH}`**, **Folder = `/docs`**. It takes a "
        f"minute or two to go live.")
    add("")
    add("---")
    add("")
    add("## 2. The two links that matter most")
    add("")
    add("| | URL |")
    add("|---|---|")
    add(f"| **The repository** | {C.GITHUB_URL} |")
    add(f"| **The live analytics portal** | {C.PAGES_URL} |")
    add("")
    add("Put both on **page 1 of the AI Methodology Report (upload slot 06)**. "
        "Suggested wording:")
    add("")
    add("> *The complete analysis — data, code, trained models and tests — is "
        f"published at `{C.GITHUB_URL.replace('https://', '')}` and runs end "
        "to end with `python run_analysis.py`. A live analytics portal is at "
        f"`{C.PAGES_URL.replace('https://', '')}`.*")
    add("")
    add("Most entries cannot offer a reproducible pipeline. It costs one line.")
    add("")
    add("---")
    add("")
    add("## 3. The 12 upload files — direct links")
    add("")
    add("GitHub renders PDFs in the browser, so these open directly. Nothing "
        "downloads and nobody has to clone anything.")
    add("")
    add("| # | Slot | Link |")
    add("|---|---|---|")
    for name, rel in rows("UPLOAD_THESE_12_FILES", "*.pdf"):
        num = name.split("_")[0]
        title = name[len(num) + 1:].replace(".pdf", "").replace("_", " ")
        add(f"| {num} | {title} | [{name}]({link(rel)}) |")
    add("")
    add("---")
    add("")
    add("## 4. The drawings")
    add("")
    add("| Drawing | Link |")
    add("|---|---|")
    for name, rel in rows("design/visuals", "*.png"):
        add(f"| {name.replace('_crescent.png', '').replace('_', ' ').title()} "
            f"| [{name}]({link(rel)}) |")
    for name, rel in rows("design/boards", "*.png"):
        add(f"| {name.replace('.png', '').replace('_', ' ').title()} "
            f"| [{name}]({link(rel)}) |")
    add("")
    add("## 5. The analysis figures")
    add("")
    add("| Figure | Link |")
    add("|---|---|")
    for name, rel in rows("figures", "*.png"):
        add(f"| {name} | [open]({link(rel)}) |")
    add("")
    add("---")
    add("")
    add("## 6. The evidence a juror can check")
    add("")
    add("| What | Link |")
    add("|---|---|")
    add(f"| **The analysis notebook** (outputs embedded — start here) "
        f"| {link('notebooks/AL_SAFA_2_PARK_COMPLETE_ANALYSIS.ipynb')} |")
    add(f"| The project plan | {link('PROJECT_PLAN.md')} |")
    add(f"| Data sources, with limitations stated | {link('DATA_SOURCES.md')} |")
    add(f"| Headline metrics (JSON) | {link('models/headline_metrics.json')} |")
    add(f"| Trained-model metrics | {link('models/model_metrics.json')} |")
    add(f"| Cost plan, line by line | {link('data/processed/cost_plan.csv')} |")
    add(f"| Room schedule | {link('data/raw/site_zoning_schedule.csv')} |")
    add(f"| The 38 pipeline tests | {link('tests/test_pipeline.py')} |")
    add(f"| The masterplan geometry generator | {link('src/plan.py')} |")
    add(f"| The cost model | {link('src/costing.py')} |")
    add(f"| Withdrawn visuals, with reasons | "
        f"{link('archive/withdrawn_visuals/README.md')} |")
    add("")
    add("## 7. The concept film")
    add("")
    add("| | Link |")
    add("|---|---|")
    add(f"| Watch it (once Pages is on) | {C.PAGES_URL} — the portal embeds it |")
    add(f"| Source | "
        f"{link('submission/12_Concept_Animation_Video/concept_film.html')} |")
    add("")
    add("> An HTML file on a `/blob/` link shows the **source code**, not the "
        "running film. To let someone watch it, either record it to MP4 and "
        "upload that, or serve it from GitHub Pages.")
    add("")
    add("---")
    add("")
    add("## 8. If you would rather not publish the repository")
    add("")
    add("Upload the twelve PDFs to Google Drive, set each to "
        "**Anyone with the link → Viewer**, and cite that folder instead. It is "
        "weaker evidence — a jury can read the reports but cannot see that the "
        "numbers regenerate — but it is better than a dead GitHub link.")
    add("")
    add("Whichever you choose: **click every link yourself before submitting.**")
    add("")

    out = ROOT / "LINKS.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")

    n_pdf = len(rows("UPLOAD_THESE_12_FILES", "*.pdf"))
    n_fig = len(rows("figures", "*.png"))
    n_dwg = len(rows("design/visuals", "*.png")) + len(rows("design/boards", "*.png"))
    print(f"  LINKS.md written")
    print(f"    {n_pdf} upload PDFs, {n_dwg} drawings, {n_fig} figures")
    print(f"    repo   {C.GITHUB_URL}")
    print(f"    portal {C.PAGES_URL}")
    if not pushed:
        print()
        print("  [!] No git remote configured - every link 404s until you push.")
        print("      LINKS.md says so at the top.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
