"""
Build the project website (GitHub Pages) into docs/.

The page is generated by scanning submission/, figures/ and models/ rather than
by hand-writing links, so a link cannot silently rot when a file is renamed.

    python tools/build_site.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from src import config as C  # noqa: E402

DOCS = ROOT / "docs"
DOCS.mkdir(exist_ok=True)

BLOB = f"{C.GITHUB_URL}/blob/main"
RAW = f"https://raw.githubusercontent.com/{C.GITHUB_USER}/{C.GITHUB_REPO}/main"

SLOTS = {
    "01_Design_Narrative_Concept": ("Design Narrative &amp; Concept", "The story: what is wrong with the park today and what the Shaded Spine does about it."),
    "02_Preliminary_Design_Masterplan": ("Preliminary Design Masterplan", "The plan at scale — zones, circulation, the area schedule that sums to 15,000 m²."),
    "03_Concept_Plans_Spatial_Diagrams": ("Concept Plans &amp; Spatial Diagrams", "How the park is organised: rooms, thresholds, and the spine that links them."),
    "04_Key_Sections_Elevations": ("Key Sections &amp; Elevations", "Cut through the spine and the entrance gateway — canopy height, span, structure."),
    "05_3D_Spatial_Visualizations": ("3D &amp; Spatial Visualisations", "Aerial day and night, eye-level through the spine and the plaza."),
    "06_AI_Methodology_Report": ("AI Methodology Report", "How AI was used — and the analysis notebook that proves it, end to end."),
    "07_User_Experience_Activation_Strategy": ("User Experience &amp; Activation", "Who uses the park, when, and what is programmed in each comfort window."),
    "08_Sustainability_Concept_Strategy": ("Sustainability Concept &amp; Strategy", "Water balance, carbon, energy — stated honestly, including the shortfalls."),
    "09_Material_Landscape_Palette": ("Material &amp; Landscape Palette", "Planting palette by species and the surface materials that go with it."),
    "10_Complete_Design_Report": ("Complete Design Report", "The flagship report — the whole argument from evidence to design."),
    "11_Site_Analysis_Human_Centric_Research": ("Site Analysis &amp; Human-Centric Research", "Climate, solar, catchment and the ranked problem definition."),
    "12_Concept_Animation_Video": ("Concept Animation Video", "Storyboard for the 60-second concept film."),
}

FIG_CAPTIONS = {
    "fig04_site_comfort_map": "Predicted summer comfort, square metre by square metre",
    "fig02_comfort_bands": "Shade converts unusable daylight hours into usable ones",
    "fig09_diurnal_comfort": "When the park is comfortable, hour by hour and month by month",
    "fig06_feature_importance": "What actually determines whether a square metre is shaded",
    "fig05_surrogate_performance": "The surrogate model against ray-traced ground truth",
    "fig07_confusion_matrix": "Predicting thermal stress from the clock and the sun alone",
    "fig01_climate_and_comfort": "Dubai climate, and what it feels like",
    "fig10_masterplan": "The masterplan, drawn from the geometry the models use",
    "fig03_shade_by_zone": "Annual shade coverage by zone type",
    "fig08_microclimate_regimes": "The park's operating regimes, found by clustering",
}

m = json.loads((ROOT / "models" / "headline_metrics.json").read_text(encoding="utf-8"))

# Read the model scores from the metrics file rather than typing them into the
# page. A hand-typed figure here is exactly how a website drifts out of step
# with the analysis it is describing.
_mm = json.loads((ROOT / "models" / "model_metrics.json").read_text(encoding="utf-8"))
_rf = _mm["M1_shade_surrogate"]["models"]["random_forest"]
_nn = _mm["M1_shade_surrogate"]["models"]["neural_network"]


def slot_cards() -> str:
    out = []
    for i, (folder, (title, blurb)) in enumerate(SLOTS.items(), start=1):
        d = ROOT / "submission" / folder
        files = sorted(d.glob("*")) if d.exists() else []
        links = "".join(
            f'<li><a href="{BLOB}/submission/{folder}/{f.name}">{f.name}</a>'
            f'<span class="sz">{f.stat().st_size / 1024:,.0f} KB</span></li>'
            for f in files if f.is_file()
        ) or "<li class='none'>No file yet</li>"
        out.append(f"""
      <article class="slot">
        <div class="num">{i:02d}</div>
        <div class="body">
          <h3>{title}</h3>
          <p>{blurb}</p>
          <ul class="files">{links}</ul>
        </div>
      </article>""")
    return "".join(out)


def figure_cards() -> str:
    out = []
    for name, cap in FIG_CAPTIONS.items():
        p = ROOT / "figures" / f"{name}.png"
        if not p.exists():
            continue
        out.append(f"""
      <figure>
        <a href="{BLOB}/figures/{name}.png"><img loading="lazy" src="{RAW}/figures/{name}.png" alt="{cap}"></a>
        <figcaption>{cap}</figcaption>
      </figure>""")
    return "".join(out)


HTML = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Al Safa 2 Park — The Shaded Spine</title>
<meta name="description" content="AI-supported redesign of Al Safa 2 Park for the Dubai Municipality AI Park Design Challenge. Complete data analysis and machine learning workflow.">
<style>
  :root {{
    color-scheme: light dark;
    --surface: {C.SURFACE_LIGHT};
    --panel: #ffffff;
    --ink: {C.PALETTE['ink']};
    --ink-2: {C.PALETTE['ink_secondary']};
    --muted: {C.PALETTE['muted']};
    --rule: {C.PALETTE['rule']};
    --accent: {C.SERIES[0]};
    --accent-2: {C.SERIES[1]};
    --good: {C.STATUS['good']};
  }}
  @media (prefers-color-scheme: dark) {{
    :root:not([data-theme="light"]) {{
      --surface: {C.SURFACE_DARK}; --panel: #232320; --ink: #ffffff;
      --ink-2: #c3c2b7; --muted: #898781; --rule: #2c2c2a;
      --accent: {C.SERIES_DARK[0]}; --accent-2: {C.SERIES_DARK[1]};
    }}
  }}
  :root[data-theme="dark"] {{
    --surface: {C.SURFACE_DARK}; --panel: #232320; --ink: #ffffff;
    --ink-2: #c3c2b7; --muted: #898781; --rule: #2c2c2a;
    --accent: {C.SERIES_DARK[0]}; --accent-2: {C.SERIES_DARK[1]};
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; background: var(--surface); color: var(--ink);
    font: 16px/1.65 system-ui, -apple-system, "Segoe UI", sans-serif;
    -webkit-font-smoothing: antialiased;
  }}
  .wrap {{ max-width: 1080px; margin: 0 auto; padding: 0 24px; }}
  a {{ color: var(--accent); text-decoration-thickness: 1px; text-underline-offset: 2px; }}

  header {{ padding: 72px 0 40px; border-bottom: 1px solid var(--rule); }}
  .eyebrow {{ font-size: 13px; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); margin: 0 0 14px; }}
  h1 {{ font-size: clamp(34px, 6vw, 60px); line-height: 1.05; margin: 0 0 18px; letter-spacing: -.02em; }}
  h1 em {{ font-style: normal; color: var(--accent); }}
  .lede {{ font-size: clamp(17px, 2.2vw, 21px); color: var(--ink-2); max-width: 62ch; margin: 0 0 28px; }}
  .cta {{ display: flex; flex-wrap: wrap; gap: 10px; }}
  .btn {{
    display: inline-block; padding: 11px 18px; border-radius: 8px;
    background: var(--accent); color: #fff; text-decoration: none; font-weight: 600; font-size: 15px;
  }}
  .btn.ghost {{ background: transparent; color: var(--ink); border: 1px solid var(--rule); }}

  section {{ padding: 52px 0; border-bottom: 1px solid var(--rule); }}
  h2 {{ font-size: 26px; margin: 0 0 8px; letter-spacing: -.01em; }}
  .sub {{ color: var(--ink-2); margin: 0 0 28px; max-width: 68ch; }}

  .kpis {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 12px; }}
  .kpi {{ background: var(--panel); border: 1px solid var(--rule); border-radius: 10px; padding: 18px; }}
  .kpi .v {{ font-size: 30px; font-weight: 700; letter-spacing: -.02em; line-height: 1.1; }}
  .kpi .l {{ font-size: 13px; color: var(--muted); margin-top: 6px; }}
  .kpi.up .v {{ color: var(--good); }}

  .callout {{
    background: var(--panel); border: 1px solid var(--rule);
    border-left: 3px solid var(--accent-2); border-radius: 10px; padding: 22px 24px;
  }}
  .callout h3 {{ margin: 0 0 10px; font-size: 18px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 15px; }}
  th, td {{ text-align: left; padding: 9px 10px; border-bottom: 1px solid var(--rule); }}
  th {{ color: var(--muted); font-weight: 600; font-size: 13px; text-transform: uppercase; letter-spacing: .04em; }}
  td.n {{ font-variant-numeric: tabular-nums; font-weight: 600; }}
  del {{ color: var(--muted); }}
  .scroll {{ overflow-x: auto; }}

  .slots {{ display: grid; gap: 12px; }}
  .slot {{ display: flex; gap: 18px; background: var(--panel); border: 1px solid var(--rule); border-radius: 10px; padding: 18px 20px; }}
  .slot .num {{ font-size: 22px; font-weight: 700; color: var(--muted); font-variant-numeric: tabular-nums; min-width: 34px; }}
  .slot h3 {{ margin: 0 0 4px; font-size: 17px; }}
  .slot p {{ margin: 0 0 10px; color: var(--ink-2); font-size: 15px; }}
  .files {{ list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 4px; }}
  .files li {{ font-size: 14px; }}
  .files .sz {{ color: var(--muted); margin-left: 8px; font-size: 12px; font-variant-numeric: tabular-nums; }}
  .files .none {{ color: var(--muted); font-style: italic; }}

  .figs {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 20px; }}
  figure {{ margin: 0; }}
  figure img {{ width: 100%; height: auto; border: 1px solid var(--rule); border-radius: 8px; display: block; background: #fff; }}
  figcaption {{ font-size: 13px; color: var(--muted); margin-top: 8px; }}

  footer {{ padding: 40px 0 70px; color: var(--muted); font-size: 14px; }}
  .toggle {{ position: fixed; top: 14px; right: 14px; background: var(--panel); border: 1px solid var(--rule);
             color: var(--ink); border-radius: 8px; padding: 7px 11px; cursor: pointer; font-size: 13px; }}
</style>
</head>
<body>
<button class="toggle" id="t">◑ theme</button>

<header><div class="wrap">
  <p class="eyebrow">Dubai Municipality · AI Park Design Challenge · 2026</p>
  <h1>Al Safa 2 Park<br><em>The Shaded Spine</em></h1>
  <p class="lede">
    A 15,000 m² neighbourhood park redesigned around one question: how do you make an
    outdoor space usable in a city that is, for half the year, too hot to stand in?
  </p>
  <div class="cta">
    <a class="btn" href="{BLOB}/notebooks/AL_SAFA_2_PARK_COMPLETE_ANALYSIS.ipynb">📓 The analysis notebook</a>
    <a class="btn ghost" href="{C.GITHUB_URL}">GitHub repository</a>
    <a class="btn ghost" href="#files">The 12 submission files</a>
    <a class="btn ghost" href="{BLOB}/DATA_SOURCES.md">Data sources</a>
  </div>
</div></header>

<section><div class="wrap">
  <h2>The result</h2>
  <p class="sub">Every figure below is regenerated by <code>python run_analysis.py</code>. None is typed by hand.</p>
  <div class="kpis">
    <div class="kpi"><div class="v">{m['daylight_hours_comfortable_exposed_pct']}%</div><div class="l">Comfortable daylight hours today</div></div>
    <div class="kpi up"><div class="v">{m['daylight_hours_comfortable_shaded_pct']}%</div><div class="l">Comfortable daylight hours as designed</div></div>
    <div class="kpi"><div class="v">{m['mean_heat_index_reduction_c']} °C</div><div class="l">Mean heat-index reduction</div></div>
    <div class="kpi"><div class="v">{m['spine_shade_canopy_plus_trees_pct']}%</div><div class="l">Annual shade on the spine</div></div>
    <div class="kpi"><div class="v">{m['model_M1_test_r2']}</div><div class="l">Shade surrogate test R²</div></div>
    <div class="kpi"><div class="v">{m['model_M2_test_accuracy']:.1%}</div><div class="l">Comfort classifier accuracy</div></div>
  </div>
</div></section>

<section><div class="wrap">
  <h2>A correction this submission makes to itself</h2>
  <p class="sub">An earlier version claimed 99.2% annual shade on the spine. It does not survive a geometric check, and it has been withdrawn.</p>
  <div class="callout">
    <h3>Why the old number was wrong</h3>
    <p>A flat 9 m canopy at 5.5 m does not shade a 9 m walkway when the sun is low and to the
    south — the shadow slides off the path. Modelled properly, hour by hour, across all
    {m['annual_daylight_hours']:,} annual daylight hours:</p>
    <div class="scroll"><table>
      <tr><th>Model</th><th>Annual shade on the spine</th></tr>
      <tr><td><del>Previously claimed</del></td><td class="n"><del>99.2%</del></td></tr>
      <tr><td>Canopy structure alone</td><td class="n">{m['spine_shade_canopy_only_pct']}%</td></tr>
      <tr><td>Canopy <strong>+ flanking tree avenue</strong></td><td class="n">{m['spine_shade_canopy_plus_trees_pct']}%</td></tr>
    </table></div>
    <p style="margin-bottom:0">The honest number is lower — and it is the <strong>better argument</strong>. It is what
    shows the tree avenue is structural to the concept rather than decoration. A scheme
    claiming 99% invites one juror with a sun-path diagram to discredit everything else.
    This one invites them to check the working.</p>
  </div>
</div></section>

<section><div class="wrap">
  <h2>The machine learning</h2>
  <p class="sub">
    Four models. The constraint on all of them: the target must not be recoverable from the
    inputs by algebra. The heat index is a closed-form function of temperature and humidity,
    so "predicting" it from temperature and humidity is arithmetic wearing a lab coat.
  </p>
  <div class="scroll"><table>
    <tr><th>Model</th><th>Task</th><th>Result</th><th>Why it is a real problem</th></tr>
    <tr><td>Random Forest</td><td>Shade surrogate</td><td class="n">R² {_rf['test_r2']:.3f}</td><td>Learns a slow ray-traced simulation from cheap plan geometry</td></tr>
    <tr><td>Neural network</td><td>Shade surrogate (deployed)</td><td class="n">R² {_nn['test_r2']:.3f}</td><td>Differentiable, so it can sit inside a layout optimiser</td></tr>
    <tr><td>Gradient Boosting</td><td>Comfort band, 4-class</td><td class="n">{m['model_M2_test_accuracy']:.1%}</td><td>Temperature and humidity <strong>withheld</strong> — sun position and calendar only</td></tr>
    <tr><td>K-Means</td><td>Microclimate regimes</td><td class="n">k = {m['model_M3_regimes']}</td><td>Unsupervised; k selected by silhouette, not chosen</td></tr>
  </table></div>
</div></section>

<section id="files"><div class="wrap">
  <h2>The 12 submission files</h2>
  <p class="sub">Mapped to the Dubai Municipality upload form. Every link goes to the file on GitHub.</p>
  <div class="slots">{slot_cards()}</div>
</div></section>

<section><div class="wrap">
  <h2>Figures</h2>
  <p class="sub">One visual system across every chart — one palette, validated for colour-vision deficiency; no dual axes anywhere; a source line on every figure.</p>
  <div class="figs">{figure_cards()}</div>
</div></section>

<section><div class="wrap">
  <h2>Honesty notes</h2>
  <p class="sub">The full version is in <a href="{BLOB}/DATA_SOURCES.md">DATA_SOURCES.md</a>.</p>
  <ul>
    <li>The climate record is <strong>39 years</strong> (NCM 1977–2015) but published as <strong>monthly normals</strong>.
        The 8,760-hour series is reconstructed from it, verified back against those normals to within
        <strong>0.39 °C</strong>, and labelled <code>MODELLED</code> everywhere it appears. Conclusions are about a
        typical year, never about extremes.</li>
    <li>The <strong>site boundary is assumed</strong> — a 150 × 100 m rectangle pending confirmation against the
        supplied DWG. Every area figure depends on it.</li>
    <li><strong>Visitor demand is a scenario model, not a machine learning result.</strong> It is deliberately
        excluded from the model suite: a model trained on it would only recover the assumption that
        produced it.</li>
    <li><strong>Diffuse radiation is excluded</strong> from the shade model, so shaded comfort is stated conservatively.</li>
  </ul>
</div></section>

<footer><div class="wrap">
  <p>Al Safa 2 Park · The Shaded Spine · Mohamed Wasim · Dubai Municipality AI Park Design Challenge 2026</p>
  <p>Built with Python, pandas, scikit-learn, pvlib and matplotlib. Reproduce everything: <code>python run_analysis.py</code></p>
</div></footer>

<script>
  const t = document.getElementById('t');
  const saved = localStorage.getItem('theme');
  if (saved) document.documentElement.setAttribute('data-theme', saved);
  t.addEventListener('click', () => {{
    const cur = document.documentElement.getAttribute('data-theme');
    const dark = cur ? cur === 'dark'
      : matchMedia('(prefers-color-scheme: dark)').matches;
    const next = dark ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    localStorage.setItem('theme', next);
  }});
</script>
</body>
</html>
"""

(DOCS / "index.html").write_text(HTML, encoding="utf-8")
print(f"wrote {DOCS / 'index.html'}  ({len(HTML):,} bytes)")


# ---------------------------------------------------------------------------
# Self-contained variant, for publishing before the repository exists.
#
# GitHub Pages can serve docs/index.html only after a push. Until then the site
# has no URL at all, so this variant inlines every figure as a data URI and
# drops the page wrapper, letting the same page be published directly. Links to
# repository files are kept — they resolve the moment the push happens — and a
# banner says plainly that they do not work yet.
# ---------------------------------------------------------------------------
import base64  # noqa: E402

art = HTML[HTML.index("<style>"):]
art = art.replace("</body>\n</html>", "").rstrip()

inlined = 0
for name in FIG_CAPTIONS:
    p = ROOT / "figures" / f"{name}.png"
    if not p.exists():
        continue
    uri = "data:image/png;base64," + base64.b64encode(p.read_bytes()).decode()
    before = art
    art = art.replace(f'src="{RAW}/figures/{name}.png"', f'src="{uri}"')
    if art != before:
        inlined += 1

banner = (
    '<div style="background:var(--panel);border:1px solid var(--rule);'
    'border-left:3px solid var(--accent-2);padding:14px 18px;margin:0 0 26px;'
    'font-size:14px;line-height:1.6;color:var(--ink-2)">'
    '<strong style="color:var(--ink)">This is the project site, published directly.</strong> '
    f'The figures below are embedded in the page. Links to files in the repository '
    f'(<code>{C.GITHUB_USER}/{C.GITHUB_REPO}</code>) resolve once it is pushed — '
    'they will not open until then.</div>'
)
art = art.replace('<header><div class="wrap">', f'<div class="wrap">{banner}</div>\n<header><div class="wrap">', 1)
art = f'<title>Al Safa 2 Park — The Shaded Spine</title>\n{art}\n'

(DOCS / "index_selfcontained.html").write_text(art, encoding="utf-8")
print(f"wrote {DOCS / 'index_selfcontained.html'}  "
      f"({len(art)/1_048_576:.2f} MB, {inlined} figures inlined)")
