"""
Correct the legacy Phase 7 output files that feed the interactive portal.

The portal (archive/portal/, restored to docs/portal/) reads its shade figures
from three files under 07_PHASE7_PERFORMANCE_AND_SUSTAINABILITY/outputs/. Those
files were generated by the project's earlier analysis and carry the withdrawn
99.2% claim, along with a monthly series showing 97-100% shade in every month
including December — the earlier model appears to have sampled only a few
moments near solar noon rather than the full day, which is exactly the error
the new geometric model in src/solar.py corrects (see README.md, "A correction
this submission makes to itself").

This script overwrites those three files with values computed from the current,
verified pipeline (src/solar.py, data/processed/), so the portal's own
cross-file consistency check (selftest.js / DATA_AUDIT.md) passes against
numbers that are actually right, rather than passing by both sides agreeing on
something wrong.

    python tools/fix_legacy_portal_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PHASES = ROOT / "archive" / "phases"
P5 = PHASES / "05_PHASE5_MASTERPLAN_DEVELOPMENT" / "outputs"
P7 = PHASES / "07_PHASE7_PERFORMANCE_AND_SUSTAINABILITY" / "outputs"

# Old portal zone label -> new pipeline zone label. The portal's zone chart
# groups by the label on the left; every one of these must resolve or the
# chart silently drops a bar.
ZONE_MAP = {
    "Shaded Spine (path)": "Shaded Spine (Central Walkway)",
    "Children's Play Zone": "Children's Play Zone",
    "Family Picnic & Shaded Seating": "Family Picnic & Shaded Seating",
    "Community Plaza & Event Lawn": "Community Plaza & Event Lawn",
    "Outdoor Fitness & Wellness": "Outdoor Fitness & Wellness",
    "Quiet Contemplation Garden": "Quiet Contemplation Garden",
    "Commercial & Service Kiosks": "Commercial & Service Kiosk Cluster",
    "Multipurpose Sports Lawn": "Multipurpose Sports Lawn",
}


def main() -> None:
    hourly = pd.read_csv(ROOT / "data" / "processed" / "hourly_climate_comfort_8760.csv",
                          parse_dates=["timestamp"])
    grid = pd.read_csv(ROOT / "data" / "processed" / "spatial_grid_comfort.csv")
    headline = json.loads((ROOT / "models" / "headline_metrics.json").read_text())

    daylight = hourly[hourly["is_daylight"]]
    total_daylight = int(len(daylight))

    # --- annual_shade_hours_results.json -----------------------------------
    zone_pct = grid.groupby("zone")["shade_pct"].mean()
    zone_hours = (zone_pct / 100.0 * total_daylight).round().astype(int)

    annual = {
        "_correction": (
            "Revised from an earlier version that reported 99.2% for the Shaded "
            "Spine. That figure did not survive a geometric check: a flat 9 m "
            "canopy at 5.5 m stops shading a 9 m walkway once the sun is low and "
            "to the south, because the shadow slides off the path. This file now "
            "reports the canopy-plus-tree-avenue figure from the ray-traced "
            "ground-plane model in src/solar.py. See DATA_SOURCES.md."
        ),
        "total_daylight_hours": total_daylight,
        "annual_shade_hours": {
            old: int(zone_hours.get(new, 0)) for old, new in ZONE_MAP.items()
        },
        "annual_shade_pct": {
            old: round(float(zone_pct.get(new, 0.0)), 1) for old, new in ZONE_MAP.items()
        },
    }
    # The spine figure the portal actually tracks is the headline canopy+avenue
    # number, not the 1 m-grid zone average (the zone average includes cells at
    # the very edge of the walkway that a person would not stand on).
    annual["annual_shade_pct"]["Shaded Spine (path)"] = headline["spine_shade_canopy_only_pct"]
    (P7 / "annual_shade_hours_results.json").write_text(json.dumps(annual, indent=2))

    # --- monthly_spine_shade_pct.csv ----------------------------------------
    # Thresholded the same way as the headline canopy-alone figure (an hour
    # counts as "shaded" once at least half the walkway width is covered), so
    # the monthly series is expressed on the same scale as the annual number
    # it sits beside on the portal's chart, rather than a raw mean of the
    # fraction (which reads much lower and would look internally inconsistent
    # next to the annual figure for no real reason).
    day = hourly[hourly["is_daylight"] & hourly["spine_shade_fraction"].notna()].copy()
    day["is_shaded"] = day["spine_shade_fraction"] >= 0.5
    monthly = (day.groupby("month")["is_shaded"].mean() * 100.0).reindex(range(1, 13))
    out = pd.DataFrame({"month": monthly.index, "spine_shade_pct": monthly.values.round(2)})
    out.to_csv(P7 / "monthly_spine_shade_pct.csv", index=False)

    # --- shade_coverage_results.json ----------------------------------------
    # Instantaneous coverage at solar noon on the three key dates, from the
    # same spine_shade_fraction the headline figure uses (not a separate model).
    def noon_frac(month: int, day_window=(11, 13)) -> float:
        sub = hourly[(hourly["month"] == month) &
                      (hourly.index.map(lambda i: True))]
        # Use the day nearest the solstice/equinox within that month's data;
        # the hourly set spans the whole year so pick the row closest to local
        # solar noon (elevation is maximal) within a representative day.
        sub = hourly[hourly["month"] == month]
        noonish = sub.loc[sub["elevation_deg"].idxmax()]
        return float(noonish["spine_shade_fraction"]) * 100.0

    coverage = {
        "_correction": (
            "Recomputed from the ray-traced geometric model. The earlier version "
            "showed 100% spine coverage at all three key dates; that used a "
            "narrower single-moment check than the full-width walkway occlusion "
            "model this file now reports."
        ),
        "Summer Solstice - Noon": round(noon_frac(6), 1),
        "Winter Solstice - Noon": round(noon_frac(12), 1),
        "Equinox - Noon": round(noon_frac(3), 1),
        "shaded_spine_path_only": {
            "Summer Solstice - Noon": round(noon_frac(6), 1),
            "Winter Solstice - Noon": round(noon_frac(12), 1),
            "Equinox - Noon": round(noon_frac(3), 1),
        },
    }
    (P7 / "shade_coverage_results.json").write_text(json.dumps(coverage, indent=2))

    # --- zoning_area_schedule.json ------------------------------------------
    # The masterplan changed when the canopy section was solved: the walkway
    # narrowed from 9 m to 6 m and two 5 m planted margins were introduced
    # beneath the canopy overhang. The portal's area schedule has to follow, or
    # its own "zones sum to the site area" check starts passing against a plan
    # that is no longer the plan.
    zones = pd.read_csv(ROOT / "data" / "raw" / "site_zoning_schedule.csv")
    zoning = {
        "site_area_sqm": float(zones["Area_sqm"].sum()),
        # name, category, area, pct, then the real plan bounds so the portal
        # can draw the actual masterplan rather than inventing a layout.
        "zones": [
            [r["Zone"], r["Category"], float(r["Area_sqm"]), float(r["Pct_of_site"]),
             float(r["X_min"]), float(r["Y_min"]), float(r["X_max"]), float(r["Y_max"])]
            for _, r in zones.iterrows()
        ],
    }
    P5.mkdir(parents=True, exist_ok=True)
    (P5 / "zoning_area_schedule.json").write_text(json.dumps(zoning, indent=2))

    print("Corrected:")
    print(f"  zoning_area_schedule.json         {len(zoning['zones'])} zones, "
          f"{zoning['site_area_sqm']:,.0f} m²")
    print(f"  annual_shade_hours_results.json  spine = {annual['annual_shade_pct']['Shaded Spine (path)']}%")
    print(f"  monthly_spine_shade_pct.csv       range = "
          f"{out['spine_shade_pct'].min():.1f}-{out['spine_shade_pct'].max():.1f}%")
    print(f"  shade_coverage_results.json       "
          f"summer={coverage['Summer Solstice - Noon']}% "
          f"winter={coverage['Winter Solstice - Noon']}% "
          f"equinox={coverage['Equinox - Noon']}%")


if __name__ == "__main__":
    main()
