"""Restock the twelve submission folders from the current outputs.

The cull left four slots holding only a PDF: the drawings that used to sit
beside them described the superseded scheme and were withdrawn. This copies the
regenerated drawings, figures and boards into the slots that need them, and
writes a MANIFEST.md into each so a reader can tell what each file is and what
produced it.

Nothing is authored here. Every image copied in is generated by
`python run_analysis.py`, `python -m src.drawings` and `python -m src.boards`,
so a slot cannot hold a picture of a design the models no longer describe.

    python tools/sync_submission.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SUB = ROOT / "submission"
FIG = ROOT / "figures"
VIS = ROOT / "design" / "visuals"
BOARD = ROOT / "design" / "boards"
REND = ROOT / "design" / "renders"

# slot -> [(source, what it is)]
PLAN: dict[str, list[tuple[Path, str]]] = {
    "01_Design_Narrative_Concept": [
        (BOARD / "board_1_concept.png",
         "Presentation board 1 — the concept, the plan and the section."),
    ],
    "02_Preliminary_Design_Masterplan": [
        (FIG / "fig10_masterplan.png",
         "The masterplan, with the numbered room schedule. Drawn from "
         "src/plan.py; every area is the shoelace area of the drawn polygon."),
        (VIS / "planting_crescent.png",
         "Planting plan — 131 trees at mature canopy radius."),
    ],
    "03_Concept_Plans_Spatial_Diagrams": [
        (FIG / "fig10_masterplan.png", "The masterplan and its room schedule."),
        (VIS / "circulation_crescent.png",
         "Circulation and accessibility — the shaded primary route, the radial "
         "sikkas, and Al Madar, the running loop."),
        (FIG / "fig04_site_comfort_map.png",
         "Predicted July comfort per square metre — the spatial argument for "
         "where each room was placed."),
    ],
    "04_Key_Sections_Elevations": [
        (VIS / "section_crescent.png",
         "Section A–A through the Crescent Canopy at midspan, with both "
         "solstice sun angles computed by the NREL algorithm."),
        (VIS / "elevation_crescent.png",
         "Long elevation — the bay rhythm, the perforated soffit and the "
         "southern louvre."),
    ],
    "05_3D_Spatial_Visualizations": [
        (BOARD / "board_1_concept.png", "Presentation board 1 — concept."),
        (BOARD / "board_2_evidence.png", "Presentation board 2 — evidence."),
        (REND / "Aerial" / "dubai_futuristic_masterplan_aerial.jpg",
         "Aerial — the canopy and the channel running the length of the crescent."),
    ],
    "08_Sustainability_Concept_Strategy": [
        (FIG / "fig03_shade_by_zone.png",
         "Ray-traced annual shade coverage by zone type."),
        (FIG / "fig02_comfort_bands.png",
         "Share of the daylight year in each comfort band, exposed and shaded."),
    ],
    "09_Material_Landscape_Palette": [
        (VIS / "planting_crescent.png",
         "Planting plan — species, counts, mature canopy and summer water demand."),
        (VIS / "section_crescent.png",
         "Section A–A, showing the surface build-up and the falaj channel."),
    ],
    "06_AI_Methodology_Report": [
        (FIG / "fig05_surrogate_performance.png",
         "The shade surrogate against ray-traced ground truth, held-out test set."),
        (FIG / "fig06_feature_importance.png",
         "Permutation importance — which design levers actually move the outcome."),
        (FIG / "fig07_confusion_matrix.png",
         "Comfort classifier, with temperature and humidity withheld."),
    ],
    "11_Site_Analysis_Human_Centric_Research": [
        (FIG / "fig01_climate_and_comfort.png",
         "Dubai monthly normals against the modelled heat index."),
        (FIG / "fig09_diurnal_comfort.png",
         "Hour-by-month comfort surface, exposed today and shaded as designed."),
    ],
}

HEADER = """# Slot {slot}

Files in this folder, and what produced each one.

| File | What it is |
|---|---|
"""

FOOTER = """
Every image here is generated. Rebuild them with:

```
python run_analysis.py      # datasets, models, figures/
python -m src.drawings      # design/visuals/ — section, elevation, circulation, planting
python -m src.boards        # design/boards/ — the two presentation boards
python tools/sync_submission.py
```

Images withdrawn from this submission, and why, are recorded in
`archive/withdrawn_visuals/README.md`.
"""


def main() -> int:
    copied = 0
    for slot, items in PLAN.items():
        dest = SUB / slot
        if not dest.exists():
            print(f"  ! missing slot folder: {slot}")
            continue
        rows = []
        for src, what in items:
            if not src.exists():
                print(f"  ! missing source: {src.relative_to(ROOT)}")
                continue
            shutil.copy2(src, dest / src.name)
            rows.append(f"| `{src.name}` | {what} |")
            copied += 1
        # Existing PDFs and documents in the slot are listed too, so the
        # manifest describes the folder rather than only what this tool wrote.
        known = {s.name for s, _ in items}
        for p in sorted(dest.iterdir()):
            if p.name in known or p.name == "MANIFEST.md" or p.suffix == ".bak":
                continue
            rows.append(f"| `{p.name}` | Written report / supporting document. |")
        (dest / "MANIFEST.md").write_text(
            HEADER.format(slot=slot.replace("_", " ")) + "\n".join(rows) + "\n" + FOOTER,
            encoding="utf-8")
        print(f"  {slot:<46} {len(items)} image(s)")

    print(f"\n{copied} file(s) copied into submission/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
