"""Restock the twelve submission folders from the current outputs.

The cull left four slots holding only a PDF: the drawings that used to sit
beside them described the superseded scheme and were withdrawn. This copies the
regenerated drawings, figures and boards into the slots that need them, and
writes a MANIFEST.md into each so a reader can tell what each file is and what
produced it.

Nothing is authored here. Every image copied in is generated by
`python run_analysis.py`, `python -m src.drawings` and `python -m src.boards`,
so a slot cannot hold a picture of a design the models no longer describe.

    python tools/sync_submission.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SUB = ROOT / "submission"
FIG = ROOT / "figures"
VIS = ROOT / "design" / "visuals"
BOARD = ROOT / "design" / "boards"
REND = ROOT / "design" / "renders"

# slot -> [(source, what it is)]
PLAN: dict[str, list[tuple[Path, str]]] = {
    "01_Design_Narrative_Concept": [
        (BOARD / "board_1_concept.png",
         "Presentation board 1 — the concept, the plan and the section."),
    ],
    "02_Preliminary_Design_Masterplan": [
        (FIG / "fig10_masterplan.png",
         "The masterplan, with the numbered room schedule. Drawn from "
         "src/plan.py; every area is the shoelace area of the drawn polygon."),
        (VIS / "planting_crescent.png",
         "Planting plan — 131 trees at mature canopy radius."),
    ],
    "03_Concept_Plans_Spatial_Diagrams": [
        (FIG / "fig10_masterplan.png", "The masterplan and its room schedule."),
        (VIS / "facilities_crescent.png",
         "Commercial & Service Facilities Map — required by the Scope of Work. "
         "Souk, cafe, restrooms, drinking fountains, waste and recycling, "
         "bicycle parking, drop-off and the service route."),
        (VIS / "circulation_crescent.png",
         "Circulation and accessibility — the shaded primary route, the radial "
         "sikkas, and Al Madar, the running loop."),
        (FIG / "fig04_site_comfort_map.png",
         "Predicted July comfort per square metre — the spatial argument for "
         "where each room was placed."),
    ],
    "04_Key_Sections_Elevations": [
        (VIS / "section_crescent.png",
         "Section A–A through the Crescent Canopy at midspan, with both "
         "solstice sun angles computed by the NREL algorithm."),
        (VIS / "elevation_crescent.png",
         "Long elevation — the bay rhythm, the perforated soffit and the "
         "southern louvre."),
    ],
    "05_3D_Spatial_Visualizations": [
        (BOARD / "board_1_concept.png", "Presentation board 1 — concept."),
        (BOARD / "board_2_evidence.png", "Presentation board 2 — evidence."),
        (FIG / "fig10_masterplan.png",
         "The masterplan the visualisations must agree with. Any render that "
         "does not show this park does not belong in this slot."),
        # The aerial is deliberately NOT listed. masterplan_aerial_golden_hour.jpg
        # exists but shows a closed oval ring, which is the plan form the sweep
        # in AL_SAFA_MASTER_PROMPT.md Section A4 tested and rejected — 79.1%
        # mean cover and 89 hours with no shade, against the arc's 52. A juror
        # reads the scheme from the aerial, and that file teaches the wrong one.
        # Re-add this line when an aerial exists that shows a single open arc.
        (REND / "Eye_Level" / "spine_corridor_interior.jpg",
         "Eye level beneath Al Hilal — artistic impression. Master prompt 03."),
        (REND / "Night" / "night_plaza_render_1784970565232.jpg",
         "The plaza at night — artistic impression. Master prompt 02."),
    ],
    "07_User_Experience_Activation_Strategy": [
        (FIG / "fig09_diurnal_comfort.png",
         "Hour-by-month comfort surface — the calendar the activation "
         "programme is built from. It is why summer midday is not programmed "
         "outdoors and late afternoon is."),
        (FIG / "fig08_microclimate_regimes.png",
         "K-Means microclimate regimes across the site, k selected by "
         "silhouette score. Different regimes take different programmes."),
        (VIS / "circulation_crescent.png",
         "Circulation and accessibility — how a visitor actually reaches each "
         "room, step-free, from the shaded primary route."),
    ],
    "10_Complete_Design_Report": [
        (FIG / "fig10_masterplan.png",
         "The masterplan and its measured room schedule, closing on 15,000 m²."),
        (BOARD / "board_2_evidence.png",
         "Presentation board 2 — the evidence behind every claim in this report."),
        (FIG / "fig11_cost_plan.png",
         "The capital cost plan against the AED 35 M ceiling, line by line."),
        (VIS / "section_crescent.png",
         "Section A–A through the Crescent Canopy — the detail the whole "
         "thermal argument rests on."),
    ],
    "12_Concept_Animation_Video": [
        (FIG / "fig10_masterplan.png",
         "The masterplan the sixty-second film flies over. Every frame of the "
         "film reads the same geometry, asserted by tests/test_film.js."),
    ],
    "08_Sustainability_Concept_Strategy": [
        (FIG / "fig03_shade_by_zone.png",
         "Ray-traced annual shade coverage by zone type."),
        (FIG / "fig02_comfort_bands.png",
         "Share of the daylight year in each comfort band, exposed and shaded."),
    ],
    "09_Material_Landscape_Palette": [
        (VIS / "planting_crescent.png",
         "Planting plan — species, counts, mature canopy and summer water demand."),
        (VIS / "section_crescent.png",
         "Section A–A, showing the surface build-up and the falaj channel."),
    ],
    "06_AI_Methodology_Report": [
        (FIG / "fig05_surrogate_performance.png",
         "The shade surrogate against ray-traced ground truth, held-out test set."),
        (FIG / "fig06_feature_importance.png",
         "Permutation importance — which design levers actually move the outcome."),
        (FIG / "fig07_confusion_matrix.png",
         "Comfort classifier, with temperature and humidity withheld."),
    ],
    "11_Site_Analysis_Human_Centric_Research": [
        (FIG / "fig01_climate_and_comfort.png",
         "Dubai monthly normals against the modelled heat index."),
        (FIG / "fig09_diurnal_comfort.png",
         "Hour-by-month comfort surface, exposed today and shaded as designed."),
    ],
}

HEADER = """# Slot {slot}

Files in this folder, and what produced each one.

| File | What it is |
|---|---|
"""

FOOTER = """
Every image here is generated. Rebuild them with:

```
python run_analysis.py      # datasets, models, figures/
python -m src.drawings      # design/visuals/ — section, elevation, circulation, planting
python -m src.boards        # design/boards/ — the two presentation boards
python tools/sync_submission.py
```

Images withdrawn from this submission, and why, are recorded in
`archive/withdrawn_visuals/README.md`.
"""


# Files that live in a slot without this tool putting them there — the films
# and the recorded video. Left to the fallback they were all described as
# "Written report / supporting document", which for a sixty-second MP4 is
# actively misleading to anyone reading the folder.
DEFAULT_WHAT = "Written report / supporting document."
DESCRIBE = {
    "Falaj_Al_Safa_Concept_Film_60s_4K.mp4":
        "**Deliverable 15 — the one-minute concept animation.** 3840x2160, "
        "sixty seconds, H.264 with AAC narration. Upload this file. Recorded "
        "from concept_film_hero.html.",
    "concept_film_hero.html":
        "The film that produced the MP4 — drawn entirely from the project's "
        "own data, no photographs. Seven plan forms swept and scored, and a "
        "heat index falling from 56.8 to 48.7 C. Press Record to rebuild the "
        "video at 1080p or 4K. Built by tools/build_concept_film_hero.py.",
    "concept_film_presentation.html":
        "An alternative cut using the six photoreal renders against the same "
        "narration, moving between the visualisations and the analysis behind "
        "them. Built by tools/build_concept_film_v2.py.",
    "concept_film.html":
        "The original real-time cut: the park drawn in 3D from src/plan.py "
        "with shadows computed live, kept because it demonstrates that the "
        "film and the drawings share one geometry. Every frame is asserted by "
        "tests/test_film.js.",
}


def main() -> int:
    copied = 0
    for slot, items in PLAN.items():
        dest = SUB / slot
        if not dest.exists():
            print(f"  ! missing slot folder: {slot}")
            continue
        rows = []
        for src, what in items:
            if not src.exists():
                print(f"  ! missing source: {src.relative_to(ROOT)}")
                continue
            shutil.copy2(src, dest / src.name)
            rows.append(f"| `{src.name}` | {what} |")
            copied += 1
        # Existing PDFs and documents in the slot are listed too, so the
        # manifest describes the folder rather than only what this tool wrote.
        known = {s.name for s, _ in items}
        for p in sorted(dest.iterdir()):
            if p.name in known or p.name == "MANIFEST.md" or p.suffix == ".bak":
                continue
            rows.append(f"| `{p.name}` | {DESCRIBE.get(p.name, DEFAULT_WHAT)} |")
        (dest / "MANIFEST.md").write_text(
            HEADER.format(slot=slot.replace("_", " ")) + "\n".join(rows) + "\n" + FOOTER,
            encoding="utf-8")
        print(f"  {slot:<46} {len(items)} image(s)")

    print(f"\n{copied} file(s) copied into submission/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
